### ISSUE TITLE
Plans to support Optimizely X?

### ISSUE THREAD

**Issue by jamesspittal** [FunnelEnvy/optimizely-cli#77]
Curious if there are any plans to extend this to support Optimizely X?

**Comment by mdcuk34** [comment]
Did you find a solution for using this or another package with X?

**Comment by jamesspittal** [comment]
Hi @mdcuk34 

> Did you find a solution for using this or another package with X?

Unfortunately not. @axs89 Any plans to extend this to support Optimizely X?

**Comment by axs89** [comment]
Hi @jamesspittal thanks for the issue and sorry for the delay. Yes there are plans, let me circle up with the team and get back to you asap.

**Comment by jamesspittal** [comment]
Thanks @axs89

**Comment by mdcuk34** [comment]
Great news, thanks @jamesspitta & @axs89, let me know if there's anything I can help you with.

**Comment by jamesspittal** [comment]
Thanks @mdcuk34

**Comment by axs89** [comment]
@jamesspittal @mdcuk34 ok you should be seeing some more specific issues created soon that we can work towards. The API is definitely one part of it, but we've also identified some other opportunities for improvement related to Optimizely X.

Oh and we'd absolutely welcome pull requests and collaboration here!

**Comment by jamesspittal** [comment]
Thanks @axs89 - that's great news.

**Comment by fredgurnot** [comment]
Hi @axs89, @jamesspittal 

A port to Optimizely X would be awesome. Would be happy to contribute as well.

**Comment by jamesspittal** [comment]
Thanks @fredgurnot - @axs89 want to jump on a call and we can talk about throwing some of our resources at this from end?

**Comment by jamesspittal** [comment]
Hey @axs89 Good to see you at Opticon. Forgot to bring this up when we caught up. Still plans to port this to support Optimizely X? CDN delays have been doing our head in lately.

**Comment by axs89** [comment]
hey @jamesspittal great to see you there as well. Stay tuned on this, @bruab is soon to make some updates that should make life easier.

**Comment by bruab** [comment]
Howdy @jamesspittal @fredgurnot @mdcuk34 ! We've got a barely-functional Optimizely X tool built out here: https://github.com/FunnelEnvy/fecli/ ([inspiration](http://startupquote.com/post/855482768))

It supports pulling an experiment, hosting it locally (including variation.css), and pushing updates.

I decided to create a new repo because we do a lot of Adobe Test & Target work, and I want to support that as well. This means I may be creating a monstrosity. Feel free to do any and all of the following:

- Open a bunch of Issues
- Submit a PR
- Fork either project and strike out on your own. (We won't be offended at all, but we'll watch with interest)
- Set up time to chat with me about how you use (and would like to use) the tools: http://calendly.com/brian-funnelenvy

cc @axs89

**Comment by jamesspittal** [comment]
Thanks @bruab - will take a look, we have something brewing internally (built out in PHP) which takes a bit of a seperate path altogether and without support for Adobe which we may or may not open source. Happy to compare notes when it's ready if you like.

**Comment by DariusCapizzi** [comment]
Hey guys, we built one out that we found useful internally, if you're interested: https://www.npmjs.com/package/@teamroboboogie/x-optimizely-cli
Let us know what you think!

**Comment by bdhhtb** [comment]
Thanks @DariusCapizzi ! Looks good. Took me forever but I added a link to x-optimizely-cli in the README.

Between [x-optimizely-cli](https://www.npmjs.com/package/@teamroboboogie/x-optimizely-cli) and [fecli](https://github.com/FunnelEnvy/fecli/) I think we've got Optimizely X covered; optimizely-cli will not be supporting it.

**Comment by jamesspittal** [comment]
Thanks @bruab
